version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: reminderping_postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-reminder_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme123}
      POSTGRES_DB: ${POSTGRES_DB:-reminderping}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - reminderping_network

  redis:
    image: redis:7.2
    container_name: reminderping_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD:-changeme123}"]
    volumes:
      - redis-data:/data
    networks:
      - reminderping_network

networks:
  reminderping_network:
    driver: bridge

volumes:
  postgres-data:
  redis-data:
